#!/usr/bin/env python3

# TODO
import os
import sys
import helpers

from analyzer import Analyzer
from termcolor import colored


def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @name")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    # get last 50 tweets from @username
    tweets = helpers.get_user_timeline(sys.argv[1], count = 50)
    # check return value
    if tweets == None:
        sys.exit("Invalid username.")

    # analyze each tweet
    for i in tweets:
        # get overall sentiment score for tweet
        score = analyzer.analyze(i)
        # print score and tweet with appropriate color
        if score > 0.0:
            print(colored(score, "green"), end= " ")
            print(colored(i, "green"))
        elif score < 0.0:
            print(colored(score, "red"), end= " ")
            print(colored(i, "red"))
        else:
            print(colored(score, "yellow"), end = " ")
            print(colored(i, "yellow"))

if __name__ == "__main__":
    main()

